version: '3.8'

services:
  api:
    build: .
    ports:
      - "5002:5000"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_URLS=http://+:5002
      - DOTNET_ENVIRONMENT=Development

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "QAContactManager2025"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"